# Import necessary packages

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import mineralML as mm
import Thermobar as pt
import os

In [2]:
#mm.__version__

# Now setup folders and paths

In [3]:
if os.name=='posix':
    slash='/'
else:
    slash='\\'

MasterFolder=os.path.dirname(os.path.dirname(os.getcwd()))

figpath=MasterFolder +slash+"Data_processing_notebooks"+slash+'Data_processing_Keana_Uwe_Litt'+slash+'Processing figs'
if not os.path.exists(figpath):
    os.mkdir(figpath)

compilation_folder=MasterFolder +slash+"Data_processing_notebooks"+slash+'Data_processing_Keana_Uwe_Litt'+slash+'Notebook_Compiled_data'
if not os.path.exists(compilation_folder):
    os.mkdir(compilation_folder)

# Now lets merge the EPMA dataframe with the Raman data

## First import the Raman data for each subset

In [4]:
K21=pd.read_excel(MasterFolder +slash+"Data_processing_notebooks"+slash+
                  'Data_processing_Keana_Uwe_Litt'+slash+
                  'Data_processing_K21'+slash+'Notebook_Compiled_data'+slash+'K21_Raman_averaged.xlsx')
L84=pd.read_excel(MasterFolder +slash+"Data_processing_notebooks"+slash+
                  'Data_processing_Keana_Uwe_Litt'+slash+
                  'Data_processing_L84'+slash+'Notebook_Compiled_data'+slash+'L84_Raman_averaged.xlsx')
UW=pd.read_excel(MasterFolder +slash+"Data_processing_notebooks"+slash+
                  'Data_processing_Keana_Uwe_Litt'+slash+
                  'Data_processing_UW'+slash+'Notebook_Compiled_data'+slash+'UW_Raman_averaged.xlsx')

## Next, merge the Raman all together

In [5]:
Raman_df=pd.concat([K21,L84,UW],axis=0)
Raman_df = Raman_df.loc[:, ~Raman_df.columns.str.contains('Unnamed')]

Raman_df

,filename,Density g/cm3,σ Density g/cm3,σ Density g/cm3 (from Ne+peakfit),σ Density g/cm3 (from densimeter),Corrected_Splitting,Corrected_Splitting_σ,Corrected_Splitting_σ_Ne,Corrected_Splitting_σ_peak_fit,power (mW),...,FI_axis_a_um_Raman_STD,FI_axis_b_um_Raman_STD,Angle_Raman_STD,pixels wide_Raman_STD,pixels high_Raman_STD,mag_Raman_STD,decrepit_Raman_STD,shape_Raman_STD,averaged?,Model_name
0,FO1_MI1-Oct2822postpin,0.093418,0.004147,0.001605,0.003803,102.986018,0.004050,0.000577,0.004014,11.974000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN
1,K21-51rep1,0.136553,0.005473,0.003755,0.003862,103.094878,0.009476,0.000554,0.009478,12.100333,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,Yes,NaN
2,K21-53-FI#4,0.017623,0.007732,0.006662,0.003925,102.794730,0.016813,0.000545,0.016841,19.972000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN
3,K21-54-FI#2,0.102444,0.004640,0.002654,0.003807,103.008795,0.006697,0.000553,0.006689,11.984000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN
4,K21-54-FI#4,0.068174,0.027324,0.027057,0.003811,102.922308,0.068284,0.000559,0.068433,11.973000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,UW7-OX6-FI#2-12mW-R1,0.134985,0.003937,0.000779,0.003858,103.090919,0.001967,0.000614,0.001871,9.061750,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,Yes,Spline
73,UW7-OX7-FI#1,0.171994,0.003587,0.002689,0.002373,103.174533,0.006629,0.000615,0.006614,12.005000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN
74,UW7-OX8-FI#1,0.120475,0.003967,0.001040,0.003829,103.054301,0.002625,0.000615,0.002557,12.012000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Spline
75,UW7-OX8-FI#2,0.126914,0.004174,0.001635,0.003840,103.070551,0.004127,0.000616,0.004090,12.025000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Spline
76,UW7-OX9-FI#1,0.143185,0.003972,0.000852,0.003880,103.111614,0.002150,0.000617,0.002064,12.044000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN

## Import the olivine data

In [6]:
OlivineEPMA=pd.read_excel(MasterFolder+slash+'Data'+slash+'Data_Kea_Uwe_Litt'+slash+'Data_all_EPMA'+
                          slash+'Devitre_olivine_041223_wtags_mod_062323.xlsx')
OlivineEPMA =OlivineEPMA.loc[:, ~OlivineEPMA.columns.str.contains('Unnamed')]

OlivineEPMA.head()

,Number order,MOUNT,Probe no.,Probe_name,old_name,Comments,Weight P,CaO,TiO2,SiO2,...,D.L,Ca(D.L.),Ti(D.L.),Si(D.L.),Al(D.L.),Mg(D.L.),Fe(D.L.),Mn(D.L.),Ni(D.L.),Cr(D.L.)
0,1,1 (CLJD),7.5,LL4-FI1-#1_avg,LL4-FI1-#1,average compo,NaN,0.235,0.018,39.269,...,NaN,68.0,95.5,113.5,43.0,49.5,95.0,85.5,53.0,61.5
1,2,1 (CLJD),12.0,LL4-FI1_2,LL4-FI1-#2,NaN,NaN,0.244,0.024,39.178,...,NaN,68.0,95.0,113.0,43.0,47.0,96.0,80.0,54.0,59.0
2,3,1 (CLJD),13.0,LL4-FI2_1,LL4-FI2,NaN,NaN,0.217,0.017,39.459,...,NaN,71.0,97.0,114.0,43.0,50.0,103.0,91.0,53.0,57.0
3,4,1 (CLJD),14.0,LL4-FI3-4_1,LL4-FI3-4-#1,NaN,NaN,0.262,0.003,39.411,...,NaN,68.0,96.0,111.0,41.0,49.0,94.0,81.0,53.0,61.0
4,5,1 (CLJD),14.0,LL4-FI3-4_1,LL4-FI3-4-MI,MI are close to FI #1,NaN,0.262,0.003,39.411,...,NaN,68.0,96.0,111.0,41.0,49.0,94.0,81.0,53.0,61.0

## Merge the olivines to the FI

In [7]:
sorted_df_renamed = OlivineEPMA.rename(columns={'Probe_name': 'Name_on_EPMA'})

# I had duplicated rows in the EPMA files with how I was merging before, eliminate duplicate rows
sorted_df_renamed = sorted_df_renamed.drop_duplicates(subset=['Name_on_EPMA']) 

#rename columns to add suffix Ol_EPMA
sorted_df_renamed = sorted_df_renamed.rename(columns=lambda x: x + '_Ol' if x != 'Name_on_EPMA' else x)

combined_df = Raman_df.merge(sorted_df_renamed, on='Name_on_EPMA', how='left')
combined_df.to_excel(compilation_folder+'/'+"K21_L84_UW_mergedEPMA.xlsx")


combined_df

,filename,Density g/cm3,σ Density g/cm3,σ Density g/cm3 (from Ne+peakfit),σ Density g/cm3 (from densimeter),Corrected_Splitting,Corrected_Splitting_σ,Corrected_Splitting_σ_Ne,Corrected_Splitting_σ_peak_fit,power (mW),...,D.L_Ol,Ca(D.L.)_Ol,Ti(D.L.)_Ol,Si(D.L.)_Ol,Al(D.L.)_Ol,Mg(D.L.)_Ol,Fe(D.L.)_Ol,Mn(D.L.)_Ol,Ni(D.L.)_Ol,Cr(D.L.)_Ol
0,FO1_MI1-Oct2822postpin,0.093418,0.004147,0.001605,0.003803,102.986018,0.004050,0.000577,0.004014,11.974000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,K21-51rep1,0.136553,0.005473,0.003755,0.003862,103.094878,0.009476,0.000554,0.009478,12.100333,...,NaN,69.0,95.0,115.0,43.0,48.0,95.0,83.0,54.0,63.0
2,K21-53-FI#4,0.017623,0.007732,0.006662,0.003925,102.794730,0.016813,0.000545,0.016841,19.972000,...,NaN,71.0,99.0,115.0,45.0,45.0,95.0,85.0,54.0,61.0
3,K21-54-FI#2,0.102444,0.004640,0.002654,0.003807,103.008795,0.006697,0.000553,0.006689,11.984000,...,NaN,70.0,99.0,115.0,43.0,45.0,96.0,80.0,52.0,59.0
4,K21-54-FI#4,0.068174,0.027324,0.027057,0.003811,102.922308,0.068284,0.000559,0.068433,11.973000,...,NaN,71.0,98.0,117.0,44.0,45.0,91.0,82.0,51.0,61.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,UW7-OX6-FI#2-12mW-R1,0.134985,0.003937,0.000779,0.003858,103.090919,0.001967,0.000614,0.001871,9.061750,...,NaN,93.0,129.0,136.0,53.0,51.0,97.0,90.0,56.0,62.0
146,UW7-OX7-FI#1,0.171994,0.003587,0.002689,0.002373,103.174533,0.006629,0.000615,0.006614,12.005000,...,NaN,91.0,126.0,140.0,52.0,51.0,100.0,94.0,55.0,61.0
147,UW7-OX8-FI#1,0.120475,0.003967,0.001040,0.003829,103.054301,0.002625,0.000615,0.002557,12.012000,...,NaN,92.0,129.0,142.0,52.0,50.0,93.0,87.0,55.0,59.0
148,UW7-OX8-FI#2,0.126914,0.004174,0.001635,0.003840,103.070551,0.004127,0.000616,0.004090,12.025000,...,NaN,92.0,129.0,142.0,52.0,50.0,93.0,87.0,55.0,59.0
149,UW7-OX9-FI#1,0.143185,0.003972,0.000852,0.003880,103.111614,0.002150,0.000617,0.002064,12.044000,...,NaN,93.0,126.0,139.0,52.0,51.0,102.0,91.0,53.0,63.0

## Now let's merge the glass data

### Function to average glass data

In [8]:
### Create reusable function to average glass data and calculate std 
# def combine_strings_with_counts(series):
#     """
#     Combine string values into 'value(count)' joined by underscores.
#     NaNs are represented as ' ' unless all values are NaN.
#     """
#     if series.isna().all():
#         return np.nan

#     filled = series.fillna(" ").astype(str)
#     counts = filled.value_counts()

#     return "_".join(f"{val}({cnt})" for val, cnt in counts.items())



def average_by_col(
    Data,
    group_col="Sample",
    suffix="_Gl",
    averaged_col_name="averaged?",
    non_numeric_behavior="first"  # NEW
):
    """
    Group a DataFrame by `group_col`, average numeric columns,
    handle non-numeric columns according to `non_numeric_behavior`,
    append STD columns, flag whether rows were averaged,
    and rename columns with a suffix.

    non_numeric_behavior:
        - "first" : keep first value per group (default)
        - "last"  : keep last value per group
        - "skip"  : drop non-numeric columns entirely
    """

    grouped = Data.groupby(group_col)

    # Separate numeric and non-numeric columns
    numeric_cols = Data.select_dtypes(include='number')
    non_numeric_cols = Data.select_dtypes(exclude='number')

    # Aggregate numeric columns
    numeric_Data_averaged_mean = grouped[numeric_cols.columns].mean()
    numeric_Data_averaged_std = grouped[numeric_cols.columns].std()

    if non_numeric_behavior == "first":
        non_numeric_Data_averaged = grouped[non_numeric_cols.columns].first()

    elif non_numeric_behavior == "last":
        non_numeric_Data_averaged = grouped[non_numeric_cols.columns].last()

    elif non_numeric_behavior == "skip":
        non_numeric_Data_averaged = (
            grouped[[group_col]].first()
            if group_col in non_numeric_cols.columns
            else None
        )
    else:
        raise ValueError(
            "non_numeric_behavior must be one of: 'first', 'last', 'skip'"
        )

    # Concatenate aggregated data
    Data_averaged = pd.concat(
        [numeric_Data_averaged_mean, non_numeric_Data_averaged]
        if non_numeric_Data_averaged is not None
        else [numeric_Data_averaged_mean],
        axis=1
    )

    if non_numeric_behavior != "skip":
        Data_averaged = Data_averaged.reindex(columns=Data.columns)

    # Add standard deviation columns
    Data_averaged = pd.concat(
        [Data_averaged, numeric_Data_averaged_std.add_suffix('_STD')],
        axis=1
    )

    # Reset index
    Data_averaged = Data_averaged.reset_index(drop=True)

    # Row counts
    row_counts = grouped.size().reset_index(name='row_count')
    row_counts[averaged_col_name] = 'No'
    row_counts['#of analyses (when averaged)'] = pd.NA
    row_counts.loc[row_counts['row_count'] > 1, '#of analyses (when averaged)'] = row_counts['row_count']
    row_counts.loc[row_counts['row_count'] > 1, averaged_col_name] = 'Yes'

    # Merge averaged flag
    Data_averaged = pd.merge(
        Data_averaged,
        row_counts[[group_col, averaged_col_name,'#of analyses (when averaged)']],
        on=group_col,
        how='left'
    )

    Data_averaged[averaged_col_name] = Data_averaged[averaged_col_name].fillna('No')
    Data_averaged['non_numeric_column_behavior_used (First/Last instance kept or skipped)'] = non_numeric_behavior
    # Rename columns
    Data_averaged_renamed = Data_averaged.rename(
        columns=lambda x: x + suffix if x != group_col else group_col
    )

    return Data_averaged_renamed

### Now import the glass data for each eruption
- Note that I don't have glass data for L84, it was never analyzed

### First, import the glass data for Kulanaokuaiki (unpublished Wieser data)

In [9]:
glasses=pd.read_excel(MasterFolder+slash+'Data'+slash+'Data_Kea_Uwe_Litt'+slash+'Data_all_EPMA'+
                          slash+'Wieser_Glasses_Explosive_Combined.xlsx').dropna(axis=0,how='all')
glasses['Eruption']='Kulanaokuaiki (400-950 CE)'

glasses.columns = glasses.columns.str.replace('_Liq', '')

glasses=glasses.rename(columns={'Comment':'Sample Name','Total':'Total_wt%','Mg Number':'Mg#'})
glasses['Sample_original']=glasses['Sample Name'].astype(str).str.split('_').str[2]

parts = glasses['Sample_original'].astype(str).str.split(')', n=1, expand=True)
glasses['Sample_original'] = parts[1].fillna(parts[0])

parts = glasses['Sample_original'].astype(str).str.split('W', n=1, expand=True)
glasses['Sample_original'] = parts[1].fillna(parts[0])
glasses.insert(0, "Sample_original", glasses.pop("Sample_original"))
glasses_averaged = average_by_col(glasses.copy(),group_col='Sample_original',non_numeric_behavior='skip')
glasses_averaged.insert(0, "Sample_original", glasses_averaged.pop("Sample_original"))

glasses_averaged['Sample'] = glasses_averaged['Sample_original'].astype(str).map({
    '0903': 'UW3',
    '0904': 'UW4',
    '0905': 'UW5',
    '0907': 'UW7',
})
glasses_averaged.insert(0, "Sample", glasses_averaged.pop("Sample"))
glasses_averaged['Reference']="[Wieser, unpublished @ Cambridge Probe lab]"
glasses_averaged

,Sample,Sample_original,time_Gl,Na2O_Gl,SiO2_Gl,MgO_Gl,Al2O3_Gl,K2O_Gl,CaO_Gl,TiO2_Gl,...,Total_wt%_STD_Gl,X_STD_Gl,Y_STD_Gl,Z_STD_Gl,Mean Z_STD_Gl,Point#_STD_Gl,averaged?_Gl,#of analyses (when averaged)_Gl,non_numeric_column_behavior_used (First/Last instance kept or skipped)_Gl,Reference
0,UW3,0903,91.645161,2.515739,48.480519,6.458455,13.241581,0.715939,11.116748,3.028626,...,0.352029,5720.857406,1324.279066,89.080850,0.072034,13.514309,Yes,31,skip,"[Wieser, unpublished @ Cambridge Probe lab]"
1,UW4,0904,130.814815,2.102178,49.209007,9.470637,12.181963,0.455396,10.351459,2.334530,...,0.571129,3699.109499,2040.649908,59.522554,0.080875,8.255707,Yes,27,skip,"[Wieser, unpublished @ Cambridge Probe lab]"
2,UW5,0905,48.909091,2.100548,49.887703,8.579918,12.543752,0.369145,10.357664,2.199158,...,0.579310,4602.659938,974.866758,72.108911,0.076335,12.156181,Yes,33,skip,"[Wieser, unpublished @ Cambridge Probe lab]"
3,UW7,0907,13.615385,2.445227,50.451046,6.088342,12.978112,0.553427,10.304046,2.900669,...,0.666811,4309.330418,1504.902291,70.274451,0.155520,7.833655,Yes,26,skip,"[Wieser, unpublished @ Cambridge Probe lab]"

### Next, glass data from Sides et al. 2014

In [10]:
Sides_glasses_og=pd.read_excel(MasterFolder+slash+'Data'+slash+'Data_Kea_Uwe_Litt'+slash+'Data_all_EPMA'+
                          slash+'41561_2014_BFngeo2140_MOESM158_ESM.xlsx', sheet_name="Matrix Glass").dropna(axis=0)
Sides_glasses_og['Sample_original']=Sides_glasses_og['Comment'].astype(str).str.split('-g|-og|_g').str[0]

### Fix non numeric columns
Sides_glasses=Sides_glasses_og.apply(pd.to_numeric, errors="coerce")
Sides_glasses[["Sample_original", "Comment", "Date", "Code", "Fountain"]] = Sides_glasses_og[["Sample_original", "Comment", "Date", "Code", "Fountain"]]
Sides_glasses=Sides_glasses.rename(columns={'Comment':'Sample Name','Total':'Total_wt%','Mg Number':'Mg#'})

### Now average
Sides_glasses_averaged = average_by_col(Sides_glasses.copy(),group_col='Sample_original',non_numeric_behavior='skip')
Sides_glasses_averaged.insert(0, "Sample_original", Sides_glasses_averaged.pop("Sample_original"))

Sides_glasses_averaged['Sample'] = Sides_glasses_averaged['Sample_original'].astype(str).map({
    '1700': 'KL0921',
    '1920': 'KL0930',
    '1974-J2': 'KL0924'
})
Sides_glasses_averaged.insert(0, "Sample", Sides_glasses_averaged.pop("Sample"))
## sub just the ones we want
Sides_glasses_averaged_sub=Sides_glasses_averaged[Sides_glasses_averaged['Sample_original'].str.contains("1700|1920|1974-J2")]

Sides_glasses_averaged_sub['Reference']="[Sides et al. 2014]"
display(Sides_glasses)
display(Sides_glasses_averaged_sub)

/opt/anaconda3/envs/py313/lib/python3.13/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,Sample Name,Date,Code,Fountain,SiO2,TiO2,Al2O3,Cr2O3,FeO,MnO,...,Ho_err,Er_err,Tm_err,Yb_err,Lu_err,Hf_err,Ta_err,Pb_err,U_err,Sample_original
0,1400-g01,1400.0,2,30.0,51.608050,2.70845,13.589400,0.01845,11.424700,0.169800,...,0.103834,0.254100,0.040206,0.223975,0.038641,0.394330,0.118306,0.470475,0.036670,1400
1,1400-g02,1400.0,2,30.0,51.608050,2.70845,13.589400,0.01845,11.424700,0.169800,...,0.087218,0.202020,0.034387,0.195925,0.033572,0.364250,0.115326,0.352395,0.035862,1400
2,1445-A-g03,1445.0,1,-1.0,52.352725,2.62385,13.540125,0.03330,10.856675,0.172225,...,0.085956,0.187320,0.032430,0.172267,0.033209,0.332133,0.086321,0.297660,0.023528,1445-A
3,1445-A-g19,1445.0,1,-1.0,52.339000,2.70470,13.872900,0.03810,11.470100,0.157000,...,0.087000,0.193480,0.034597,0.190400,0.028304,0.345920,0.089748,0.223860,0.024795,1445-A
4,1500-1-g02,1500.0,3,600.0,50.792450,2.46925,13.407150,0.05360,11.179750,0.170900,...,0.180380,0.425600,0.068902,0.370600,0.065800,0.792107,0.295517,0.835170,0.063903,1500-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,L_o_28_g,-1.0,6,-1.0,48.179200,2.81770,12.387700,0.06550,11.880300,0.191000,...,0.067314,0.165170,0.025504,0.144180,0.025502,0.447860,15.000000,1.063867,0.060190,L_o_28
171,L_o_37_g,-1.0,6,-1.0,48.334200,2.86810,12.062650,0.04150,11.316250,0.171100,...,0.062211,0.141100,0.022400,0.121040,0.022006,0.359333,12.454955,0.972293,0.055978,L_o_37
172,L_o_39_g,-1.0,6,-1.0,49.124000,2.86985,12.224250,0.06935,12.369450,0.180900,...,0.080990,0.171810,0.028416,0.141510,0.026215,0.480200,14.527027,1.171600,0.058812,L_o_39
173,L_o_41_g,-1.0,6,-1.0,48.725100,2.88285,11.994300,0.06075,12.083350,0.177750,...,0.064673,0.164340,0.026240,0.148037,0.025751,0.472360,13.400901,1.008653,0.060424,L_o_41
174,L_o_42_g,-1.0,6,-1.0,48.833833,2.91600,11.995433,0.05610,11.805533,0.176667,...,0.069657,0.169597,0.024352,0.143883,0.024574,0.417480,12.995495,0.976333,0.054886,L_o_42

,Sample,Sample_original,Date_Gl,Code_Gl,Fountain_Gl,SiO2_Gl,TiO2_Gl,Al2O3_Gl,Cr2O3_Gl,FeO_Gl,...,Yb_err_STD_Gl,Lu_err_STD_Gl,Hf_err_STD_Gl,Ta_err_STD_Gl,Pb_err_STD_Gl,U_err_STD_Gl,averaged?_Gl,#of analyses (when averaged)_Gl,non_numeric_column_behavior_used (First/Last instance kept or skipped)_Gl,Reference
6,KL0921,1700,1700.0,2.0,-1.0,50.22478,2.437790,12.516225,0.078035,11.755390,...,0.069964,0.013791,0.136311,0.066689,0.177975,0.012990,Yes,5,skip,[Sides et al. 2014]
14,KL0930,1920,1919.0,1.0,-1.0,50.69257,2.889870,13.716000,0.043770,10.819120,...,0.011181,0.002024,0.026435,0.009491,0.048747,0.007986,Yes,5,skip,[Sides et al. 2014]
36,KL0924,1974-J2,1974.2,2.0,-1.0,50.46995,2.577625,13.236525,0.070175,11.479125,...,0.002204,0.002081,0.008419,0.006076,0.067840,0.002687,Yes,2,skip,[Sides et al. 2014]

### Now combine the two glass sets
- We also drop the error columns because these are now means, so we report STD instead

In [11]:
combo_glasses=pd.concat([glasses_averaged,Sides_glasses_averaged_sub],axis=0)
combo_glasses=combo_glasses.drop(columns=combo_glasses.columns[combo_glasses.columns.str.contains("_err", case=False)])

combo_glasses.to_excel(compilation_folder+'/'+"UW_L84_K21_averaged.xlsx")
combo_glasses

,Sample,Sample_original,time_Gl,Na2O_Gl,SiO2_Gl,MgO_Gl,Al2O3_Gl,K2O_Gl,CaO_Gl,TiO2_Gl,...,Er_STD_Gl,Tm_STD_Gl,Yb_STD_Gl,Lu_STD_Gl,Hf_STD_Gl,Ta_STD_Gl,Pb_STD_Gl,U_STD_Gl,Temp_STD_Gl,Mg#_STD_Gl
0,UW3,0903,91.645161,2.515739,48.480519,6.458455,13.241581,0.715939,11.116748,3.028626,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,UW4,0904,130.814815,2.102178,49.209007,9.470637,12.181963,0.455396,10.351459,2.334530,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,UW5,0905,48.909091,2.100548,49.887703,8.579918,12.543752,0.369145,10.357664,2.199158,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,UW7,0907,13.615385,2.445227,50.451046,6.088342,12.978112,0.553427,10.304046,2.900669,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,KL0921,1700,NaN,2.210220,50.224780,8.984445,12.516225,0.375345,10.535360,2.437790,...,0.908381,0.122262,0.823109,0.126524,1.450112,0.447574,0.482317,0.136742,2.651636,0.766843
14,KL0930,1920,NaN,2.357000,50.692570,6.991370,13.716000,0.529650,11.472840,2.889870,...,0.109707,0.025994,0.131542,0.018568,0.281222,0.063696,0.132107,0.084060,1.494865,0.598471
36,KL0924,1974-J2,NaN,2.316175,50.469950,7.242550,13.236525,0.451825,11.119225,2.577625,...,0.094281,0.019799,0.025927,0.019092,0.089567,0.040776,0.183848,0.028284,0.986372,0.261594

## Now merge and export the merged data

In [12]:
combo_glasses['Sample'] = combo_glasses['Sample_original'].astype(str).map({
    '1700': 'K21',
    '1920': 'KL0930',
    '1974-J2': 'KL0924',
    '0903':"UW3",
    '0904':'UW4',
    '0905':"UW5",
    '0907':"UW7"
})
combo_glasses

,Sample,Sample_original,time_Gl,Na2O_Gl,SiO2_Gl,MgO_Gl,Al2O3_Gl,K2O_Gl,CaO_Gl,TiO2_Gl,...,Er_STD_Gl,Tm_STD_Gl,Yb_STD_Gl,Lu_STD_Gl,Hf_STD_Gl,Ta_STD_Gl,Pb_STD_Gl,U_STD_Gl,Temp_STD_Gl,Mg#_STD_Gl
0,UW3,0903,91.645161,2.515739,48.480519,6.458455,13.241581,0.715939,11.116748,3.028626,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,UW4,0904,130.814815,2.102178,49.209007,9.470637,12.181963,0.455396,10.351459,2.334530,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,UW5,0905,48.909091,2.100548,49.887703,8.579918,12.543752,0.369145,10.357664,2.199158,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,UW7,0907,13.615385,2.445227,50.451046,6.088342,12.978112,0.553427,10.304046,2.900669,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,K21,1700,NaN,2.210220,50.224780,8.984445,12.516225,0.375345,10.535360,2.437790,...,0.908381,0.122262,0.823109,0.126524,1.450112,0.447574,0.482317,0.136742,2.651636,0.766843
14,KL0930,1920,NaN,2.357000,50.692570,6.991370,13.716000,0.529650,11.472840,2.889870,...,0.109707,0.025994,0.131542,0.018568,0.281222,0.063696,0.132107,0.084060,1.494865,0.598471
36,KL0924,1974-J2,NaN,2.316175,50.469950,7.242550,13.236525,0.451825,11.119225,2.577625,...,0.094281,0.019799,0.025927,0.019092,0.089567,0.040776,0.183848,0.028284,0.986372,0.261594

In [13]:
combined_df['Sample'].unique()

<StringArray>
['FO1', 'K21', 'L84', 'FG04', 'UW3', 'UW4', 'UW5', 'UW7']
Length: 8, dtype: str

In [14]:
combined_df['Sample'] = combined_df['Sample'].astype(str)
combined_df_wglass = combined_df.merge(combo_glasses, on='Sample', how='left')
# combined_df_wglass.to_clipboard(excel=True)
combined_df_wglass.to_excel(compilation_folder+slash+'UW_K21_L84_Raman_EDS_Gl_Merged.xlsx')

combined_df_wglass

,filename,Density g/cm3,σ Density g/cm3,σ Density g/cm3 (from Ne+peakfit),σ Density g/cm3 (from densimeter),Corrected_Splitting,Corrected_Splitting_σ,Corrected_Splitting_σ_Ne,Corrected_Splitting_σ_peak_fit,power (mW),...,Er_STD_Gl,Tm_STD_Gl,Yb_STD_Gl,Lu_STD_Gl,Hf_STD_Gl,Ta_STD_Gl,Pb_STD_Gl,U_STD_Gl,Temp_STD_Gl,Mg#_STD_Gl
0,FO1_MI1-Oct2822postpin,0.093418,0.004147,0.001605,0.003803,102.986018,0.004050,0.000577,0.004014,11.974000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,K21-51rep1,0.136553,0.005473,0.003755,0.003862,103.094878,0.009476,0.000554,0.009478,12.100333,...,0.908381,0.122262,0.823109,0.126524,1.450112,0.447574,0.482317,0.136742,2.651636,0.766843
2,K21-53-FI#4,0.017623,0.007732,0.006662,0.003925,102.794730,0.016813,0.000545,0.016841,19.972000,...,0.908381,0.122262,0.823109,0.126524,1.450112,0.447574,0.482317,0.136742,2.651636,0.766843
3,K21-54-FI#2,0.102444,0.004640,0.002654,0.003807,103.008795,0.006697,0.000553,0.006689,11.984000,...,0.908381,0.122262,0.823109,0.126524,1.450112,0.447574,0.482317,0.136742,2.651636,0.766843
4,K21-54-FI#4,0.068174,0.027324,0.027057,0.003811,102.922308,0.068284,0.000559,0.068433,11.973000,...,0.908381,0.122262,0.823109,0.126524,1.450112,0.447574,0.482317,0.136742,2.651636,0.766843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,UW7-OX6-FI#2-12mW-R1,0.134985,0.003937,0.000779,0.003858,103.090919,0.001967,0.000614,0.001871,9.061750,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146,UW7-OX7-FI#1,0.171994,0.003587,0.002689,0.002373,103.174533,0.006629,0.000615,0.006614,12.005000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,UW7-OX8-FI#1,0.120475,0.003967,0.001040,0.003829,103.054301,0.002625,0.000615,0.002557,12.012000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,UW7-OX8-FI#2,0.126914,0.004174,0.001635,0.003840,103.070551,0.004127,0.000616,0.004090,12.025000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,UW7-OX9-FI#1,0.143185,0.003972,0.000852,0.003880,103.111614,0.002150,0.000617,0.002064,12.044000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Now let's merge the EBSD
- Note that some EBSD for UW does not exist.

In [15]:
EBSD_data=pd.read_excel(MasterFolder +slash+"Data"+slash+'Data_Kea_Uwe_Litt'+slash+'EBSD'+slash+'Combined_EBSD'+slash+'EBSD_combined_all.xlsx')
EBSD_data=EBSD_data.rename(columns={'EBSD_name':'EBSD_simple_name','grainID':'EBSD_grainID','Filename':'EBSD_filename'})

final_df=pd.merge(left=combined_df_wglass,on=['EBSD_simple_name','EBSD_grainID'],right=EBSD_data,suffixes=('', '_EBSDdata'),how='left')

##### Export fully merge data ####

final_df.to_excel(compilation_folder+slash+"Kea_Uwe_Litt_Final_data_wEBSD.xlsx")
final_df

,filename,Density g/cm3,σ Density g/cm3,σ Density g/cm3 (from Ne+peakfit),σ Density g/cm3 (from densimeter),Corrected_Splitting,Corrected_Splitting_σ,Corrected_Splitting_σ_Ne,Corrected_Splitting_σ_peak_fit,power (mW),...,equivalentRadius (um),GB Length/Sqrt Size,Total GB length,Tilt length,Twist length,Perc Tilt,Perc Twist,Perc unclassified,subgrain_angle,grain_div_angle
0,FO1_MI1-Oct2822postpin,0.093418,0.004147,0.001605,0.003803,102.986018,0.004050,0.000577,0.004014,11.974000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,K21-51rep1,0.136553,0.005473,0.003755,0.003862,103.094878,0.009476,0.000554,0.009478,12.100333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,K21-53-FI#4,0.017623,0.007732,0.006662,0.003925,102.794730,0.016813,0.000545,0.016841,19.972000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,K21-54-FI#2,0.102444,0.004640,0.002654,0.003807,103.008795,0.006697,0.000553,0.006689,11.984000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,K21-54-FI#4,0.068174,0.027324,0.027057,0.003811,102.922308,0.068284,0.000559,0.068433,11.973000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,UW7-OX6-FI#2-12mW-R1,0.134985,0.003937,0.000779,0.003858,103.090919,0.001967,0.000614,0.001871,9.061750,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146,UW7-OX7-FI#1,0.171994,0.003587,0.002689,0.002373,103.174533,0.006629,0.000615,0.006614,12.005000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,UW7-OX8-FI#1,0.120475,0.003967,0.001040,0.003829,103.054301,0.002625,0.000615,0.002557,12.012000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,UW7-OX8-FI#2,0.126914,0.004174,0.001635,0.003840,103.070551,0.004127,0.000616,0.004090,12.025000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,UW7-OX9-FI#1,0.143185,0.003972,0.000852,0.003880,103.111614,0.002150,0.000617,0.002064,12.044000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN