# Import necessary packages

In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import mineralML as mm
import Thermobar as pt
import os

In [24]:
# %pip install Diadfit
# %pip install Thermobar
#mm.__version__

# Now setup folders and paths

In [25]:
if os.name=='posix':
    slash='/'
else:
    slash='\\'

MasterFolder=os.path.dirname(os.path.dirname(os.getcwd()))

# #Folder to save figures

# figpath=MasterFolder +slash+'Figs'
# if not os.path.exists(figpath):
#     os.mkdir(figpath)

# #Folder to save full datasets

compilation_folder=MasterFolder +slash+"Data_processing_notebooks"+slash+'Data_processing_Ulu_mounts'+slash+'Notebook_Compiled_data'
if not os.path.exists(compilation_folder):
    os.mkdir(compilation_folder)

# Now lets merge the SEM dataframe with the Raman data

## First import the Raman data

In [26]:
Raman_df=pd.read_excel(compilation_folder+slash+'Ulu_Raman_averaged.xlsx')
Raman_df = Raman_df.loc[:, ~Raman_df.columns.str.contains('Unnamed')]

Raman_df

,filename,Density g/cm3,σ Density g/cm3,σ Density g/cm3 (from Ne+peakfit),σ Density g/cm3 (from densimeter),Corrected_Splitting,Corrected_Splitting_σ,Corrected_Splitting_σ_Ne,Corrected_Splitting_σ_peak_fit,power (mW),...,EBSD_grainID_Raman_STD,Area_Raman_STD,FI_axis_a_um_Raman_STD,FI_axis_b_um_Raman_STD,Angle_Raman_STD,pixels wide_Raman_STD,pixels high_Raman_STD,mag_Raman_STD,real image width(um)_Raman_STD,averaged?
0,FG04-A1-1-evening_r2,0.598161,0.002916,0.001698,0.002370,104.141808,0.003491,0.000728,0.003422,6.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
1,FG04-A1-1-50X-evening-r2,0.622736,0.003053,0.001919,0.002375,104.192018,0.003896,0.000608,0.003857,5.998,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
2,FG04-A1-1_eve_r2_100X,0.647180,0.004943,0.004333,0.002380,104.241355,0.008691,0.000858,0.008667,6.041,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
3,FG04-A1-1-100X-eve-r2,0.622901,0.005599,0.005070,0.002375,104.192354,0.010295,0.000737,0.010291,6.017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
4,FG04-A1-1-100X-eve-r2,0.598815,0.006060,0.005577,0.002370,104.143151,0.011461,0.000612,0.011469,6.019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,KL0931_c034_a1_FIH,0.108702,0.010465,0.009746,0.003812,103.024588,0.024596,0.000566,0.024641,10.076,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
200,KL0931_c159_a1_FIA,0.077921,0.010195,0.009458,0.003803,102.946907,0.023870,0.000692,0.023912,9.931,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
201,KL0931_c160_a1_FIA,0.150407,0.009614,0.008787,0.003901,103.129840,0.022175,0.000695,0.022212,9.976,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
202,KL0931_c240_a1_FIA,0.107876,0.005193,0.003527,0.003812,103.022505,0.008902,0.000829,0.008883,10.029,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
203,KL0931_c240_a1_FIB,0.090379,0.009066,0.008230,0.003801,102.978346,0.020771,0.000831,0.020799,10.015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No

## Import the olivine data

In [27]:
OlivineEDS=pd.read_excel(compilation_folder+slash+'EDS_olivine.xlsx')
OlivineEDS =OlivineEDS.loc[:, ~OlivineEDS.columns.str.contains('Unnamed')]
# OlivineEDS=OlivineEDS[~OlivineEDS["Sample Name"].str.contains("K20")]
# OlivineEDS.to_clipboard(excel=True,index=False)
OlivineEDS.head()

,Sample Name,Total_wt%,Total_Oxide%,CaO,Cr2O3,Cu,FeOt,MgO,MnO,NiO,...,Line_Si,Line_Ca,Line_Cr,Line_Mn,Line_Fe,Line_Ni,Line_Cu,Line_Ti,SampleID,Fo
0,KL0910_c002_a1,98.7263,98.7263,0.2064,0.1098,NaN,11.1484,46.9748,0.1470,0.4845,...,K series,K series,K series,K series,K series,K series,NaN,NaN,KL0910_c002_a1,0.882503
1,KL0910_c002_a2,98.6295,98.6295,0.2213,0.0657,NaN,11.1721,46.9172,0.1571,0.5120,...,K series,K series,K series,K series,K series,K series,NaN,NaN,KL0910_c002_a2,0.882155
2,KL0910_c002_a3,99.0120,99.0120,0.2149,0.0913,NaN,11.2782,47.0410,0.1418,0.4746,...,K series,K series,K series,K series,K series,K series,NaN,NaN,KL0910_c002_a3,0.881445
3,KL0910_c002_a4,99.8217,99.8217,0.2277,0.0982,NaN,11.2334,47.4573,0.1568,0.4712,...,K series,K series,K series,K series,K series,K series,NaN,NaN,KL0910_c002_a4,0.882775
4,KL0910_c003_a1,100.0885,100.0885,0.2684,0.0749,NaN,14.1037,45.2653,0.1882,0.4046,...,K series,K series,K series,K series,K series,K series,NaN,NaN,KL0910_c003_a1,0.851212

In [28]:
Raman_df['Name_on_SEM']

0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN
            ...
199     KL0931_c034_a1
200    KL0931_c0159_a1
201    KL0931_c0160_a1
202     KL0931_c240_a1
203     KL0931_c240_a1
Name: Name_on_SEM, Length: 204, dtype: str

## Merge the olivines to the FI

In [29]:
sorted_df_renamed = OlivineEDS.rename(columns={'Sample Name': 'Name_on_SEM'})

sorted_df_renamed = sorted_df_renamed.rename(columns=lambda x: x + '_Ol' if x != 'Name_on_SEM' else x)

combined_df = Raman_df.merge(sorted_df_renamed, on='Name_on_SEM', how='left')
combined_df

,filename,Density g/cm3,σ Density g/cm3,σ Density g/cm3 (from Ne+peakfit),σ Density g/cm3 (from densimeter),Corrected_Splitting,Corrected_Splitting_σ,Corrected_Splitting_σ_Ne,Corrected_Splitting_σ_peak_fit,power (mW),...,Line_Si_Ol,Line_Ca_Ol,Line_Cr_Ol,Line_Mn_Ol,Line_Fe_Ol,Line_Ni_Ol,Line_Cu_Ol,Line_Ti_Ol,SampleID_Ol,Fo_Ol
0,FG04-A1-1-evening_r2,0.598161,0.002916,0.001698,0.002370,104.141808,0.003491,0.000728,0.003422,6.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FG04-A1-1-50X-evening-r2,0.622736,0.003053,0.001919,0.002375,104.192018,0.003896,0.000608,0.003857,5.998,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FG04-A1-1_eve_r2_100X,0.647180,0.004943,0.004333,0.002380,104.241355,0.008691,0.000858,0.008667,6.041,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FG04-A1-1-100X-eve-r2,0.622901,0.005599,0.005070,0.002375,104.192354,0.010295,0.000737,0.010291,6.017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FG04-A1-1-100X-eve-r2,0.598815,0.006060,0.005577,0.002370,104.143151,0.011461,0.000612,0.011469,6.019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,KL0931_c034_a1_FIH,0.108702,0.010465,0.009746,0.003812,103.024588,0.024596,0.000566,0.024641,10.076,...,K series,K series,K series,K series,K series,K series,NaN,NaN,KL0931_c034_a1,0.820462
200,KL0931_c159_a1_FIA,0.077921,0.010195,0.009458,0.003803,102.946907,0.023870,0.000692,0.023912,9.931,...,K series,K series,K series,K series,K series,K series,NaN,NaN,KL0931_c0159_a1,0.876869
201,KL0931_c160_a1_FIA,0.150407,0.009614,0.008787,0.003901,103.129840,0.022175,0.000695,0.022212,9.976,...,K series,K series,K series,K series,K series,K series,NaN,NaN,KL0931_c0160_a1,0.879759
202,KL0931_c240_a1_FIA,0.107876,0.005193,0.003527,0.003812,103.022505,0.008902,0.000829,0.008883,10.029,...,K series,K series,K series,K series,K series,K series,NaN,NaN,KL0931_c240_a1,0.821061
203,KL0931_c240_a1_FIB,0.090379,0.009066,0.008230,0.003801,102.978346,0.020771,0.000831,0.020799,10.015,...,K series,K series,K series,K series,K series,K series,NaN,NaN,KL0931_c240_a1,0.821061

## Now let's merge the glass data for Ulu

### Now let's get the Ulu data (1974) from Wieser et al. 2021

In [30]:
Ulu_all=pd.read_excel(MasterFolder+slash+"Data"+slash+"Data_Ulu_mounts"+slash+"41467_2019_13635_MOESM4_ESM_mod.xlsx",
                         sheet_name='Glass Chemistry').dropna(axis=0,how='all')
Ulu_all['Eruption']=Ulu_all['Eruption'].astype('str')

Ulu_all_filt=Ulu_all.loc[:,(~Ulu_all.columns.str.contains('ppm|corrected|Duration|Spot|Batch'))]
Ulu_all_filt.columns = Ulu_all_filt.columns.str.replace('_Liq', '')
Ulu_all_filt=Ulu_all_filt.rename(columns={'Eruption':'Sample','Glass Fragment ID':'Sample Name','Total':'Total_wt%','Mg Number':'Mg#'})
Ulu_all_filt['Sample'] = Ulu_all_filt['Sample'].astype(str).str.split('.').str[0]
Ulu_all_filt_renamed =Ulu_all_filt.rename(columns=lambda x: x + '_Gl' if x != 'Sample' else 'Sample')

Ulu_all_filt_renamed.to_excel(compilation_folder+'/'+"UluGlass_averaged.xlsx")


Ulu_all_filt_renamed

,Sample,Sample Name_Gl,Mg#_Gl,SiO2_Gl,TiO2_Gl,Al2O3_Gl,Cr2O3_Gl,FeO_Gl,MnO_Gl,MgO_Gl,...,TiO2_STD_Gl,Al2O3_STD_Gl,Cr2O3_STD_Gl,FeO_STD_Gl,MnO_STD_Gl,MgO_STD_Gl,CaO_STD_Gl,Na2O_STD_Gl,K2O_STD_Gl,P2O5_STD_Gl
0,KL0909,KL0909_mean,58.910389,50.566133,2.697917,13.587583,0.065833,10.472667,0.115333,7.419267,...,0.109080,1.262459,0.030850,1.124124,0.047954,1.985284,1.908187,0.576458,0.165210,0.052990
1,KL0908,KL0908_mean,62.758571,49.074900,2.564245,12.547055,0.068882,11.344236,0.181982,9.137145,...,0.066675,0.289078,0.058311,0.464987,0.048246,0.689945,0.234062,0.120551,0.052242,0.028655
2,KL0917,KL0917_mean,52.666723,50.309225,2.808325,13.770642,0.013275,11.378208,0.196467,6.035833,...,0.042624,0.286115,0.042682,0.372266,0.029538,0.145275,0.258969,0.116300,0.021497,0.023686
3,KL0922,KL0922_mean,53.322905,50.214711,2.799378,13.693411,0.011778,11.458622,0.172644,6.243511,...,0.044227,0.320827,0.020752,0.302914,0.052842,0.212617,0.288764,0.092164,0.048576,0.038286
4,KL0916,KL0916_mean,53.621184,49.582308,2.813469,13.522938,0.013392,11.413323,0.171315,6.292477,...,0.051717,0.258283,0.034769,0.350621,0.040360,0.179207,0.144956,0.157545,0.058021,0.033931
5,KL0914,KL0914_mean,51.043908,49.819100,3.052188,13.372063,0.001012,11.812575,0.191862,5.873950,...,0.055804,0.208950,0.041667,0.364027,0.049243,0.205614,0.199890,0.087458,0.028197,0.036792
6,KL0931,KL0931_mean,52.037886,50.176744,2.986422,13.693200,-0.004222,11.637733,0.192211,6.020644,...,0.082599,0.184863,0.035973,0.293625,0.037379,0.128953,0.259323,0.130135,0.054947,0.032684
7,KL0910,KL0910_mean,58.078790,49.975887,2.550625,13.214425,0.049450,11.263013,0.235400,7.438537,...,0.042428,0.249410,0.023303,0.363742,0.043851,0.106141,0.275847,0.056379,0.031669,0.014004
8,KL0919,KL0919_mean,61.580152,49.627473,2.209264,12.781345,0.055691,11.185364,0.184055,8.548364,...,0.575517,0.201025,0.036326,0.485520,0.052834,0.345314,0.244691,0.232906,0.102489,0.026481
9,KL0920,KL0920_mean,58.494484,49.994483,2.565167,13.352833,0.062642,11.167200,0.191325,7.520200,...,0.062908,0.310474,0.038234,0.418576,0.043366,0.518369,0.265880,0.143043,0.033981,0.034962

### And let's get the Sides et al. (2014)

In [31]:
Sides_glasses_og=pd.read_excel(MasterFolder +slash+"Data_processing_notebooks"+slash+'Data_processing_Keana_Uwe_Litt'+ 
                               slash +'Notebook_Compiled_data'+slash+"UW_L84_K21_averaged.xlsx").dropna(axis=0,how='all')

Sides_glasses_og =Sides_glasses_og.loc[:, ~Sides_glasses_og.columns.str.contains('Unnamed')].copy()
Sides_glasses_og

,Sample,Sample_original,time_Gl,Na2O_Gl,SiO2_Gl,MgO_Gl,Al2O3_Gl,K2O_Gl,CaO_Gl,TiO2_Gl,...,Er_STD_Gl,Tm_STD_Gl,Yb_STD_Gl,Lu_STD_Gl,Hf_STD_Gl,Ta_STD_Gl,Pb_STD_Gl,U_STD_Gl,Temp_STD_Gl,Mg#_STD_Gl
0,UW3,0903,91.645161,2.515739,48.480519,6.458455,13.241581,0.715939,11.116748,3.028626,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,UW4,0904,130.814815,2.102178,49.209007,9.470637,12.181963,0.455396,10.351459,2.334530,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,UW5,0905,48.909091,2.100548,49.887703,8.579918,12.543752,0.369145,10.357664,2.199158,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,UW7,0907,13.615385,2.445227,50.451046,6.088342,12.978112,0.553427,10.304046,2.900669,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,KL0921,1700,NaN,2.210220,50.224780,8.984445,12.516225,0.375345,10.535360,2.437790,...,0.908381,0.122262,0.823109,0.126524,1.450112,0.447574,0.482317,0.136742,2.651636,0.766843
5,KL0930,1920,NaN,2.357000,50.692570,6.991370,13.716000,0.529650,11.472840,2.889870,...,0.109707,0.025994,0.131542,0.018568,0.281222,0.063696,0.132107,0.084060,1.494865,0.598471
6,KL0924,1974-J2,NaN,2.316175,50.469950,7.242550,13.236525,0.451825,11.119225,2.577625,...,0.094281,0.019799,0.025927,0.019092,0.089567,0.040776,0.183848,0.028284,0.986372,0.261594

### Combine the glasses together

In [32]:
merged_glasses=pd.concat([Ulu_all_filt_renamed,Sides_glasses_og],axis=0)
merged_glasses

,Sample,Sample Name_Gl,Mg#_Gl,SiO2_Gl,TiO2_Gl,Al2O3_Gl,Cr2O3_Gl,FeO_Gl,MnO_Gl,MgO_Gl,...,Ho_STD_Gl,Er_STD_Gl,Tm_STD_Gl,Yb_STD_Gl,Lu_STD_Gl,Hf_STD_Gl,Ta_STD_Gl,Pb_STD_Gl,U_STD_Gl,Temp_STD_Gl
0,KL0909,KL0909_mean,58.910389,50.566133,2.697917,13.587583,0.065833,10.472667,0.115333,7.419267,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,KL0908,KL0908_mean,62.758571,49.074900,2.564245,12.547055,0.068882,11.344236,0.181982,9.137145,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,KL0917,KL0917_mean,52.666723,50.309225,2.808325,13.770642,0.013275,11.378208,0.196467,6.035833,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,KL0922,KL0922_mean,53.322905,50.214711,2.799378,13.693411,0.011778,11.458622,0.172644,6.243511,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,KL0916,KL0916_mean,53.621184,49.582308,2.813469,13.522938,0.013392,11.413323,0.171315,6.292477,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,KL0914,KL0914_mean,51.043908,49.819100,3.052188,13.372063,0.001012,11.812575,0.191862,5.873950,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,KL0931,KL0931_mean,52.037886,50.176744,2.986422,13.693200,-0.004222,11.637733,0.192211,6.020644,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,KL0910,KL0910_mean,58.078790,49.975887,2.550625,13.214425,0.049450,11.263013,0.235400,7.438537,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,KL0919,KL0919_mean,61.580152,49.627473,2.209264,12.781345,0.055691,11.185364,0.184055,8.548364,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,KL0920,KL0920_mean,58.494484,49.994483,2.565167,13.352833,0.062642,11.167200,0.191325,7.520200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,UW3,NaN,NaN,48.480519,3.028626,13.241581,0.030032,10.962777,0.015532,6.458455,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,UW4,NaN,NaN,49.209007,2.334530,12.181963,0.064767,11.153659,0.017722,9.470637,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,UW5,NaN,NaN,49.887703,2.199158,12.543752,0.067718,11.043461,0.016855,8.579918,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,UW7,NaN,NaN,50.451046,2.900669,12.978112,0.030212,11.403208,0.016527,6.088342,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,KL0921,NaN,60.228035,50.224780,2.437790,12.516225,0.078035,11.755390,0.178455,8.984445,...,0.374635,0.908381,0.122262,0.823109,0.126524,1.450112,0.447574,0.482317,0.136742,2.651636
5,KL0930,NaN,56.156330,50.692570,2.889870,13.716000,0.043770,10.819120,0.166110,6.991370,...,0.070971,0.109707,0.025994,0.131542,0.018568,0.281222,0.063696,0.132107,0.084060,1.494865
6,KL0924,NaN,55.569025,50.469950,2.577625,13.236525,0.070175,11.479125,0.198150,7.242550,...,0.037005,0.094281,0.019799,0.025927,0.019092,0.089567,0.040776,0.183848,0.028284,0.986372

## Now merge and export the merged data

In [33]:
combined_df['Sample'] = combined_df['Sample'].astype(str)
combined_df_wglass = combined_df.merge(merged_glasses, on='Sample', how='left')
# combined_df_wglass.to_clipboard(excel=True)

combined_df_wglass.to_excel(compilation_folder+slash+'Ulu_Raman_EDS_Gl_Merged.xlsx')

combined_df_wglass

,filename,Density g/cm3,σ Density g/cm3,σ Density g/cm3 (from Ne+peakfit),σ Density g/cm3 (from densimeter),Corrected_Splitting,Corrected_Splitting_σ,Corrected_Splitting_σ_Ne,Corrected_Splitting_σ_peak_fit,power (mW),...,Ho_STD_Gl,Er_STD_Gl,Tm_STD_Gl,Yb_STD_Gl,Lu_STD_Gl,Hf_STD_Gl,Ta_STD_Gl,Pb_STD_Gl,U_STD_Gl,Temp_STD_Gl
0,FG04-A1-1-evening_r2,0.598161,0.002916,0.001698,0.002370,104.141808,0.003491,0.000728,0.003422,6.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FG04-A1-1-50X-evening-r2,0.622736,0.003053,0.001919,0.002375,104.192018,0.003896,0.000608,0.003857,5.998,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FG04-A1-1_eve_r2_100X,0.647180,0.004943,0.004333,0.002380,104.241355,0.008691,0.000858,0.008667,6.041,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FG04-A1-1-100X-eve-r2,0.622901,0.005599,0.005070,0.002375,104.192354,0.010295,0.000737,0.010291,6.017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FG04-A1-1-100X-eve-r2,0.598815,0.006060,0.005577,0.002370,104.143151,0.011461,0.000612,0.011469,6.019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,KL0931_c034_a1_FIH,0.108702,0.010465,0.009746,0.003812,103.024588,0.024596,0.000566,0.024641,10.076,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
200,KL0931_c159_a1_FIA,0.077921,0.010195,0.009458,0.003803,102.946907,0.023870,0.000692,0.023912,9.931,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201,KL0931_c160_a1_FIA,0.150407,0.009614,0.008787,0.003901,103.129840,0.022175,0.000695,0.022212,9.976,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202,KL0931_c240_a1_FIA,0.107876,0.005193,0.003527,0.003812,103.022505,0.008902,0.000829,0.008883,10.029,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,KL0931_c240_a1_FIB,0.090379,0.009066,0.008230,0.003801,102.978346,0.020771,0.000831,0.020799,10.015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Now let's merge the EBSD

## First load the EBSD data from Wieser et al and merge the GOS params with Slip System params

In [34]:
## This loads data from Wieser et al and merges GOS with slip systems and linear intercept data.

ebsd_all_kil=pd.read_excel(MasterFolder+slash+"Data"+slash+"Data_Ulu_mounts"+slash+"EBSD"+slash+"PWCambridge"+slash+"Merged_GOS_Parameters_edited_Kil.xlsx", 
                           sheet_name="Sheet1")
ebsd_all_kil['length_norm']=ebsd_all_kil['subBoundaryLength (um)']/ebsd_all_kil['equivalentRadius (um)']
ebsd_all_kil['to_merge']= ebsd_all_kil['Filename'] + '_' + np.round(ebsd_all_kil['GOS'], 3).astype(str)

slip_sys_kil=pd.read_excel(MasterFolder+slash+"Data"+slash+"Data_Ulu_mounts"+slash+"EBSD"+slash+"PWCambridge"+slash+"Merged_GOS_Parameters_edited_Kil.xlsx",
                            sheet_name='SlipSystemID')

slip_sys_kil['file_mod']=slip_sys_kil['file'].str.replace('\'', '')
slip_sys_kil['to_merge']= slip_sys_kil['file_mod'] + '_' + np.round(slip_sys_kil['GOS'], 3).astype(str)

# Average out the linear intercepts
slip_sys_kil['mean_length'] = slip_sys_kil.loc[:, 'len1':'len20'].mean(axis=1, skipna=True)
slip_sys_kil['median_length'] = slip_sys_kil.loc[:, 'len1':'len20'].median(axis=1, skipna=True)

## combine
combined_df_kil=pd.merge(ebsd_all_kil, slip_sys_kil, on='to_merge', how='outer', suffixes=('', '_dup'))
combined_df_kil = combined_df_kil.loc[:, ~combined_df_kil.columns.str.endswith('_dup')]

combined_df_kil=combined_df_kil.fillna(0)
combined_df_kil

,Filename,Deformed,Slip_system,Blue_direction,Red_direction,Notes,Day,grainID,GOS,Grain Size (pixels),...,len14,len15,len16,len17,len18,len19,len20,file_mod,mean_length,median_length
0,\Expl_600,Y,Y,SE,NE,0,100,80,1.413278,20896,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,\Expl_600,195.100778,157.160961
1,\Expl_601,N,0,0,0,0,100,20,0.126191,409,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.000000,0.000000
2,\Expl_601,N,0,0,0,0,100,2,0.180567,253,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.000000,0.000000
3,\Expl_601,Y,Y,E,0,0,100,62,0.798379,23094,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,\Expl_601,158.124051,130.973873
4,\Expl_602,M,0,0,0,0,100,33,0.355086,180,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
793,\ulubsmallolivines_95l,N,0,0,0,0,100,10,0.134468,465,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.000000,0.000000
794,\ulubsmallolivines_95l,N,0,0,0,0,100,7,0.153968,1520,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.000000,0.000000
795,\ulubsmallolivines_95l,Y,0,0,0,0,100,15,0.463183,1954,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.000000,0.000000
796,\ulubsmallolivines_97,N,0,0,0,0,100,80,0.198164,9306,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.000000,0.000000
797,\ulubsmallolivines_97,N,0,0,0,0,100,32,0.557869,198,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.000000,0.000000

## We also have to load an merge the new EBSD data from  UCB

In [35]:
ebsd_ucb=pd.read_excel(MasterFolder+slash+"Data"+slash+"Data_Ulu_mounts"+slash+"EBSD"+slash+"UCB"+slash+"EBSD_combined_UCB_all.xlsx", 
                           sheet_name="Sheet1")
cam_ucb_ebsd=pd.concat([combined_df_kil, ebsd_ucb])

cam_ucb_ebsd.to_excel(MasterFolder+slash+"Data"+slash+"Data_Ulu_mounts"+slash+"EBSD"+slash+"Combined_EBSD"+slash+'Ulu_EBSD_combined_all.xlsx')
cam_ucb_ebsd

,Filename,Deformed,Slip_system,Blue_direction,Red_direction,Notes,Day,grainID,GOS,Grain Size (pixels),...,len17,len18,len19,len20,file_mod,mean_length,median_length,Perc Tilt,Perc Twist,Perc unclassified
0,\Expl_600,Y,Y,SE,NE,0,100,80,1.413278,20896,...,0.0,0.0,0.0,0.0,\Expl_600,195.100778,157.160961,NaN,NaN,NaN
1,\Expl_601,N,0,0,0,0,100,20,0.126191,409,...,0.0,0.0,0.0,0.0,0,0.000000,0.000000,NaN,NaN,NaN
2,\Expl_601,N,0,0,0,0,100,2,0.180567,253,...,0.0,0.0,0.0,0.0,0,0.000000,0.000000,NaN,NaN,NaN
3,\Expl_601,Y,Y,E,0,0,100,62,0.798379,23094,...,0.0,0.0,0.0,0.0,\Expl_601,158.124051,130.973873,NaN,NaN,NaN
4,\Expl_602,M,0,0,0,0,100,33,0.355086,180,...,0.0,0.0,0.0,0.0,0,0.000000,0.000000,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,\KL0917_c084,N,NaN,NaN,NaN,NaN,5222025,329,0.091376,635,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
252,\KL0917_c089,N,NaN,NaN,NaN,NaN,5222025,31,0.077540,11056,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
253,\KL0931_c021,N,NaN,NaN,NaN,NaN,5222025,28,0.109096,13123,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
254,\KL0931_c028,N,NaN,NaN,NaN,NaN,5222025,56,0.086884,11086,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
255,\KL0931_c031,N,NaN,NaN,NaN,NaN,5222025,50,0.087838,13540,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0

## Now let's merge with the rest of the data from above

In [36]:
EBSD_data=pd.read_excel(MasterFolder +slash+"Data"+slash+"Data_Ulu_mounts"+slash+"EBSD"+slash+"Combined_EBSD"+slash+'Ulu_EBSD_combined_all.xlsx')
EBSD_data=EBSD_data.rename(columns={'EBSD_name':'EBSD_simple_name','grainID':'EBSD_grainID','Filename':'EBSD_filename'})
EBSD_data['EBSD_simple_name']=EBSD_data['EBSD_filename'].copy()

final_df=pd.merge(left=combined_df_wglass,on=['EBSD_simple_name','EBSD_grainID'],right=EBSD_data,suffixes=('', '_EBSDdata'),how='left')

# ##### Export fully merge data ####

final_df.to_excel(compilation_folder+slash+"Ulu_Final_data_wEBSD.xlsx")
final_df

,filename,Density g/cm3,σ Density g/cm3,σ Density g/cm3 (from Ne+peakfit),σ Density g/cm3 (from densimeter),Corrected_Splitting,Corrected_Splitting_σ,Corrected_Splitting_σ_Ne,Corrected_Splitting_σ_peak_fit,power (mW),...,len17,len18,len19,len20,file_mod,mean_length,median_length,Perc Tilt,Perc Twist,Perc unclassified
0,FG04-A1-1-evening_r2,0.598161,0.002916,0.001698,0.002370,104.141808,0.003491,0.000728,0.003422,6.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FG04-A1-1-50X-evening-r2,0.622736,0.003053,0.001919,0.002375,104.192018,0.003896,0.000608,0.003857,5.998,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FG04-A1-1_eve_r2_100X,0.647180,0.004943,0.004333,0.002380,104.241355,0.008691,0.000858,0.008667,6.041,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FG04-A1-1-100X-eve-r2,0.622901,0.005599,0.005070,0.002375,104.192354,0.010295,0.000737,0.010291,6.017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FG04-A1-1-100X-eve-r2,0.598815,0.006060,0.005577,0.002370,104.143151,0.011461,0.000612,0.011469,6.019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,KL0931_c034_a1_FIH,0.108702,0.010465,0.009746,0.003812,103.024588,0.024596,0.000566,0.024641,10.076,...,0.0,0.0,0.0,0.0,0,0.000000,0.000000,NaN,NaN,NaN
200,KL0931_c159_a1_FIA,0.077921,0.010195,0.009458,0.003803,102.946907,0.023870,0.000692,0.023912,9.931,...,0.0,0.0,0.0,0.0,\ulubigolivines_159,282.308029,282.308029,NaN,NaN,NaN
201,KL0931_c160_a1_FIA,0.150407,0.009614,0.008787,0.003901,103.129840,0.022175,0.000695,0.022212,9.976,...,0.0,0.0,0.0,0.0,0,0.000000,0.000000,NaN,NaN,NaN
202,KL0931_c240_a1_FIA,0.107876,0.005193,0.003527,0.003812,103.022505,0.008902,0.000829,0.008883,10.029,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
203,KL0931_c240_a1_FIB,0.090379,0.009066,0.008230,0.003801,102.978346,0.020771,0.000831,0.020799,10.015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0